# -*- coding: utf-8 -*-
"""wser-splits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJtkvP9nZi43VH86kk5bK1upDq9zryHe
"""

# Commented out IPython magic to ensure Python compatibility.
######## PACKAGES AND USEFUL FUNCTIONS ########
# Import packages
# %tensorflow_version 2.x
import warnings, logging, os
logging.disable(logging.WARNING)
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
warnings.simplefilter(action='ignore', category=FutureWarning)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.preprocessing import StandardScaler

# Functions to format times
def getHours(strTime):
  if "-" in strTime:
    strTime = strTime[0:str.find(strTime,"-")]
  if " " in strTime:
    strTime= strTime[0:str.find(strTime," ")]
  if strTime == "nan" or len(strTime) == 0 or "DN" in strTime:
      return 30.0
  else:
      strTime = str.split(strTime,':')
      while len(strTime) < 3:
        strTime.append('00')
      return float(strTime[0]) + float(strTime[1])/60.0 + float(strTime[2])/3600.0

def hoursToString(hrs):
  hours = np.floor(hrs).astype(int)
  fractionalHour = hrs - hours
  seconds = fractionalHour * 3600
  minutes = np.floor(seconds / 60).astype(int)
  seconds = seconds - 60*minutes
  return "%02d:%02d:%02.1f"%(hours,minutes,seconds)

######## USER INPUTS ########
# Get input labels
print("Select location of target split: ")
aidStations = ['Robinson Flat', "Miller's Defeat", "Dusty Corners", "Devil's Thumb", 'El Dorado Creek', 'Michigan Bluff', 'Foresthill', 'Rucky Chucky']
for j in range(0, len(aidStations)):
  print(f"({j+1}) {aidStations[j]}")

aidStationNumber = -1
while aidStationNumber < 1 or aidStationNumber > len(aidStations):
  aidStationNumber = int(input("> "))
  if aidStationNumber < 1 or aidStationNumber > len(aidStations):
    print("Please enter a valid aid station number.")
targetAidStation = aidStations[aidStationNumber-1]

# Get input features
inputFeatures = []
inputFeatures.append(1.0 if str.upper(input("Gender Category (M/F): ")).strip() == 'M' else 0.0)
inputFeatures.append(int(input("Age: ")))
inputFeatures.append(float(input("Low Temperature (F): ")))
inputFeatures.append(float(input("High Temperature (F): ")))
inputFeatures.append(float(input("Snowpack at Olympic Valley (in): ")))
inputFeatures.append(getHours(input("Target Finish Time (hh:mm:ss): ")))

######## DEFINE FEATURES AND LABELS ########

# Define key aid stations (where we want to know target split)
keyAidStations = [targetAidStation]

# Define features and labels
features = ['Gender', 'Age', 'MinTemp', 'MaxTemp', 'Snow', 'Time']
labels = keyAidStations

######## LOAD TRAINING AND TESTING DATA ########

# Temperature data (F, max and min) (from https://www.wser.org/weather/)
temps = {
    2024: [94, 63],
    2023: [80, 51],
    2022: [97, 70],
    2021: [101, 73],
    2020: [93, 66],
    2019: [83, 57],
    2018: [98, 61],
    2017: [95, 75],
    2016: [93, 60],
    2015: [91, 73],
    2014: [89, 59],
    2013: [102, 73],
    2012: [71, 51],
    2011: [82, 60],
    2010: [91, 66],
    2009: [99, 61],
    2007: [87, 53],
    2006: [101, 60],
    2005: [78, 51],
    2004: [87, 57]
}

# Snowpack (in) (from https://www.wser.org/weather/)
snow = {
    2024: 0,
    2023: 6.3,
    2022: 0,
    2021: 0,
    2020: 0,
    2019: 19.6,
    2018: 0,
    2017: 22.0,
    2016: 0,
    2015: 0,
    2014: 0,
    2013: 0,
    2012: 0,
    2011: 60.9,
    2010: 17.3,
    2009: 0,
    2007: 0,
    2006: 18.0,
    2005: 25.0,
    2004: 0.0
}

# Define time ranges for available data
startTrain = 2007
endTrain = 2023
testYear = 2015

# Column Renames
columnRenames = {"Elapsed Time": "Time",
                 "Devils Thumb": "Devil's Thumb",
                 "Foresthill School": "Foresthill",
                 "Millers Defeat": "Miller's Defeat",
                 'Rucky Chucky (near)': 'Rucky Chucky',
                 'Duncan Canyon Arrived ': 'Duncan Canyon',
                 'Robinson Flat Arrived': 'Robinson Flat',
                 "Miller's Defeat Arrive": "Miller's Defeat",
                 "Dusty Corners Arrive": "Dusty Corners",
                 "Last Chance Arrive": "Last Chance",
                 "Devil's Thumb Arrive": "Devil's Thumb",
                 "El Dorado Creek Arrive": "El Dorado Creek",
                 "Michigan Bluff Arrive": "Michigan Bluff",
                 "Foresthill School Arrive": "Foresthill",
                 "River Crossing (Near)": "Rucky Chucky",
                 "Rucky Chuck (near) Arrive": "Rucky Chucky",
                 "Auburn Lake Trails Arrive": "Auburn Lake Trails",
                 "El Dorado Canyon": "El Dorado Creek",
                 'ALT': 'Auburn Lake Trails',
                 "Gen": "Gender"}


# Populate dataframes
df_train = []
df_test = []
skipyears = [2020, 2008]
if targetAidStation == 'Robinson Flat':
  skipyears.append(2011)
  skipyears.append(2012)

for year in range(startTrain,endTrain+1):
  if (year not in skipyears):
    # Account for formatting of different years headers'
    skiprows=0
    if year <= 2009:
      skiprows = 2
    df = pd.read_csv(f'wser{year}.csv', skiprows=skiprows)
    df = df.rename(columns=columnRenames)
    df = df[df['Michigan Bluff'] != 'Michigan Bluff']   # remove format errors
    df = df[df['Michigan Bluff'] != 'Elapsed']          # remove format errors

    # Add weather
    df['MaxTemp'] = temps[year][0]
    df['MinTemp'] = temps[year][1]
    df['Snow'] = snow[year]

    # Format as times
    for i in range(0, len(keyAidStations)):
      df[keyAidStations[i]] = df[keyAidStations[i]].apply(lambda x: getHours(str(x)))
      if year <= 2009:
        df[keyAidStations[i]] = df[keyAidStations[i]].apply(lambda x: x - 5)    # prior to 2010, splits are formatted as time of day (account for 5am start)
    df["Time"] = df["Time"].apply(lambda x: getHours(str(x)))

    # Format gender
    df['Gender'] = df['Gender'].apply(lambda x: 1.0 if x == 'M' else 0.0)

    # Remove DNF
    mask1 = df['Time'] >= 30
    df = df[~mask1]
    mask2 = df[targetAidStation] >= 30
    df = df[~mask2]

    # Save to appropriate dataset (train or test)
    if year != testYear:
      df_train.append(df)
    else:
      df_test = df

df_train = pd.concat(df_train)

# Input data (features) in desired format
input_train = df_train[features].copy().to_numpy(dtype=float)
input_test = df_test[features].copy().to_numpy(dtype=float)

# Output data (labels) in desired format
output_train = df_train[labels].copy().to_numpy(dtype=float)
output_test= df_test[labels].copy().to_numpy(dtype=float)

######## CREATE REGRESSION MODEL ########
normalizer = tf.keras.layers.Normalization(axis=-1) # create pre-processing layer
normalizer.adapt(np.array(input_train))             # fit state of pre-processing layer to data
model = tf.keras.Sequential([
    normalizer,
    tf.keras.layers.Dense(48, activation='relu'),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(units=len(labels))
])

# Compile model
model.compile(
    optimizer=tf.keras.optimizers.Adam(0.001),
    loss='mean_absolute_error')

# Fit model
print("Training model...")
if aidStationNumber < 8:
  epochs = 48
else:
  epochs = 24
history = model.fit(
    input_train,
    output_train,
    epochs=epochs,
    verbose=1,
    validation_split=0.15
)

print(f"Training Loss: {history.history['loss'][-1]}")
print(f"Testing Loss: {history.history['val_loss'][-1]}")

######## EVALUATE MODEL ########

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(['Train', 'Test'])
plt.grid()
plt.title('DNN Loss')
plt.show()

predictions = model.predict(input_test)

plt.scatter(output_test, predictions, s=12)
plt.xlabel('Actual Split (hr)')
plt.ylabel('Predicted Split (hr)')
plt.title('Actual vs. Predicted Splits')
plt.axis('equal')
plt.grid()
plt.show()

plt.scatter(df_test['Time'], output_test, s=12)
plt.plot(df_test['Time'], predictions, color='orange')
plt.xlabel('Finish Time (hr)')
plt.ylabel(f'{targetAidStation} Split (hr)')
plt.title(f'Finish Time vs. {targetAidStation} Split')
plt.legend(['Actual', 'Predicted'], loc='upper left')
plt.axis('equal')
plt.grid()
plt.show()

######## PREDICT TARGET SPLIT ########
# Run through model
inputFeatures
inputFeatures = np.array(inputFeatures).reshape(1,-1).astype(float)
predictedSplit = model.predict(inputFeatures)

print(f"Target {targetAidStation} Split: {hoursToString(predictedSplit[0][0])}")